import { Link } from 'react-router-dom';

export default function Privacy() {
  return (
    <div className="legal-page">
      <div className="container">
        <Link to="/" className="legal-back">&larr; Back to Home</Link>
        <h1>Privacy Policy</h1>
        <p className="legal-updated">Last updated: March 26, 2026</p>

        <h2>1. Information We Collect</h2>
        <p>Receptionist LA ("we," "us," or "our") collects the following information when you use our AI receptionist service:</p>
        <ul>
          <li><strong>Business Information:</strong> Business name, address, phone number, email, hours of operation, and services offered — provided during onboarding to configure your AI receptionist.</li>
          <li><strong>Call Data:</strong> Incoming call recordings, transcriptions, caller phone numbers, call duration, and call summaries generated by our AI system.</li>
          <li><strong>Account Information:</strong> Email address and password used to access your dashboard.</li>
          <li><strong>Payment Information:</strong> Billing details processed securely through Stripe. We do not store credit card numbers on our servers.</li>
          <li><strong>Website Usage:</strong> We use Google Analytics to collect anonymized browsing data (pages visited, time on site, device type).</li>
        </ul>

        <h2>2. How We Use Your Information</h2>
        <ul>
          <li>To provide and improve our AI receptionist service</li>
          <li>To configure and train your custom AI assistant</li>
          <li>To send call summaries and notifications</li>
          <li>To process payments and manage your subscription</li>
          <li>To communicate with you about your account and service updates</li>
          <li>To improve our AI models and service quality</li>
        </ul>

        <h2>3. Data Sharing</h2>
        <p>We do not sell your personal information. We share data only with:</p>
        <ul>
          <li><strong>Vapi.ai:</strong> Our voice AI platform provider that processes calls</li>
          <li><strong>Twilio:</strong> Our telephony provider for phone number management</li>
          <li><strong>Stripe:</strong> Our payment processor</li>
          <li><strong>Google Analytics:</strong> For anonymized website usage statistics</li>
        </ul>

        <h2>4. Data Retention</h2>
        <p>We retain call recordings and transcriptions for 90 days. Account and business information is retained for the duration of your subscription and 30 days after cancellation. You may request deletion of your data at any time by contacting us.</p>

        <h2>5. Data Security</h2>
        <p>We use industry-standard security measures including encrypted data transmission (TLS/SSL), secure password hashing, and access controls. However, no method of transmission over the Internet is 100% secure.</p>

        <h2>6. Your Rights</h2>
        <p>Under California law (CCPA), you have the right to:</p>
        <ul>
          <li>Know what personal information we collect</li>
          <li>Request deletion of your personal information</li>
          <li>Opt out of the sale of personal information (we do not sell data)</li>
          <li>Non-discrimination for exercising your privacy rights</li>
        </ul>

        <h2>7. Contact Us</h2>
        <p>For privacy-related questions or requests, contact us at:</p>
        <p>Email: <a href="mailto:admin@receptionistla.com">admin@receptionistla.com</a></p>
        <p>Phone: (844) 492-2681</p>
      </div>
    </div>
  );
}
